openapi: 3.1.0
info:
  title: Hydrosat STAC Catalog API
  version: '0.1'
tags:
- name: Catalog
paths:
  /:
    get:
      tags:
      - Catalog
      summary: Landing Page
      description: Endpoint.
      operationId: Landing_Page__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LandingPage'
  /conformance:
    get:
      tags:
      - Catalog
      summary: Conformance Classes
      description: Endpoint.
      operationId: Conformance_Classes_conformance_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conformance'
components:
  schemas:
    Conformance:
      properties:
        conformsTo:
          items:
            type: string
            minLength: 1
            format: uri
          type: array
          title: Conformsto
      type: object
      required:
      - conformsTo
      title: Conformance
      description: https://github.com/radiantearth/stac-api-spec/blob/master/api-spec.md#ogc-api---features-endpoints
    MimeTypes:
      type: string
      enum:
      - image/tiff; application=geotiff
      - image/tiff; application=geotiff; profile=cloud-optimized
      - image/jp2
      - image/png
      - image/jpeg
      - application/geo+json
      - application/geo+json-seq
      - application/geopackage+sqlite3
      - application/vnd.google-earth.kml+xml
      - application/vnd.google-earth.kmz
      - application/x-protobuf
      - application/vnd.mapbox-vector-tile
      - application/x-hdf
      - application/x-hdf5
      - application/xml
      - application/json
      - application/ndjson
      - text/html
      - text/plain
      - application/vnd.oai.openapi+json;version=3.0
      - application/vnd.oai.openapi;version=3.0
      - application/schema+json
      - application/pdf
      - text/csv
      - application/vnd.apache.parquet
      - application/octet-stream
      title: MimeTypes
      description: https://github.com/radiantearth/stac-spec/blob/v1.0.0/item-spec/item-spec.md#media-types
    Link:
      properties:
        href:
          type: string
          minLength: 1
          title: Href
        rel:
          type: string
          minLength: 1
          title: Rel
        type:
          anyOf:
          - $ref: '#/components/schemas/MimeTypes'
          - type: string
          - type: 'null'
          title: Type
        title:
          anyOf:
          - type: string
          - type: 'null'
          title: Title
      additionalProperties: true
      type: object
      required:
      - href
      - rel
      title: Link
      description: https://github.com/radiantearth/stac-spec/blob/v1.0.0/collection-spec/collection-spec.md#link-object
    LandingPage:
      properties:
        id:
          type: string
          minLength: 1
          title: Id
        description:
          type: string
          minLength: 1
          title: Description
        stac_version:
          type: string
          pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
          title: Stac Version
          default: 1.0.0
        links:
          $ref: '#/components/schemas/stac_pydantic__api__links__Links'
        stac_extensions:
          anyOf:
          - items:
              type: string
              minLength: 1
              format: uri
            type: array
          - type: 'null'
          title: Stac Extensions
          default: []
        title:
          anyOf:
          - type: string
          - type: 'null'
          title: Title
        type:
          type: string
          const: Catalog
          title: Type
        conformsTo:
          items:
            type: string
            minLength: 1
            format: uri
          type: array
          title: Conformsto
          default:
          - https://api.stacspec.org/v1.0.0/core
          - http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core
      additionalProperties: true
      type: object
      required:
      - id
      - description
      - links
      - type
      title: LandingPage
      description: 'https://github.com/radiantearth/stac-api-spec/tree/v1.0.0/core

        https://github.com/radiantearth/stac-api-spec/tree/v1.0.0/ogcapi-features#landing-page-

        https://github.com/radiantearth/stac-api-spec/tree/v1.0.0/item-search#link-relations'
    stac_pydantic__api__links__Links:
      items:
        anyOf:
        - $ref: '#/components/schemas/SearchLink'
        - $ref: '#/components/schemas/PaginationLink'
        - $ref: '#/components/schemas/ItemsLink'
        - $ref: '#/components/schemas/Link'
      type: array
      title: Links
    ItemsLink:
      properties:
        href:
          type: string
          pattern: .*\/items(\?.*)?\b
          title: Href
        rel:
          type: string
          enum:
          - self
          - items
          title: Rel
        type:
          type: string
          const: application/geo+json
          title: Type
          default: application/geo+json
        title:
          anyOf:
          - type: string
          - type: 'null'
          title: Title
        method:
          type: string
          enum:
          - GET
          - POST
          title: Method
          default: GET
        headers:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Headers
        body:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Body
        merge:
          type: boolean
          title: Merge
          default: false
      additionalProperties: true
      type: object
      required:
      - href
      - rel
      title: ItemsLink
    SearchLink:
      properties:
        href:
          type: string
          pattern: .*\/search(\?.*)?\b
          title: Href
        rel:
          type: string
          enum:
          - self
          - search
          - next
          - prev
          title: Rel
        type:
          type: string
          const: application/geo+json
          title: Type
          default: application/geo+json
        title:
          anyOf:
          - type: string
          - type: 'null'
          title: Title
        method:
          type: string
          enum:
          - GET
          - POST
          title: Method
          default: GET
        headers:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Headers
        body:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Body
        merge:
          type: boolean
          title: Merge
          default: false
      additionalProperties: true
      type: object
      required:
      - href
      - rel
      title: SearchLink
      description: https://github.com/radiantearth/stac-api-spec/tree/v1.0.0/item-search#link-relations
    PaginationLink:
      properties:
        href:
          type: string
          minLength: 1
          title: Href
        rel:
          type: string
          enum:
          - next
          - prev
          title: Rel
        type:
          anyOf:
          - $ref: '#/components/schemas/MimeTypes'
          - type: string
          - type: 'null'
          title: Type
        title:
          anyOf:
          - type: string
          - type: 'null'
          title: Title
        method:
          type: string
          enum:
          - GET
          - POST
          title: Method
          default: GET
        headers:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Headers
        body:
          anyOf:
          - additionalProperties: true
            type: object
          - type: 'null'
          title: Body
        merge:
          type: boolean
          title: Merge
          default: false
      additionalProperties: true
      type: object
      required:
      - href
      - rel
      title: PaginationLink
      description: https://github.com/radiantearth/stac-api-spec/blob/v1.0.0/item-search/README.md#pagination
